# Generated by Django 6.0.7 on 2026-08-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_admin_review', 'Pending Admin Review'), ('active', 'Active & Verified'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending_admin_review', max_length=30)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Standard baseline rate in CAD/hr', max_digits=6, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skill tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_shifts', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_earned', models.DecimalField(blank=True, decimal_places=2, help_text="Caregiver's 85% share", max_digits=8, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=15)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_note', models.TextField(blank=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='Account.shift')),
            ],
        ),
    ]
