# Generated by Django 6.0.7 on 2026-08-04 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_caregiverprofile_shift_shiftlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('psw_certificate', 'PSW Certificate'), ('vulnerable_sector_check', 'Vulnerable Sector Check'), ('government_id', 'Government ID'), ('first_aid', 'First Aid / CPR Certificate'), ('resume', 'Resume / CV'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='caregiver_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('note', models.TextField(blank=True, help_text='Admin review note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
