# Generated by Django 6.0.5 on 2026-08-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_caregiverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name as it appears on the account', max_length=150),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='bank_institution_number',
            field=models.CharField(blank=True, help_text='3-digit institution number', max_length=5),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='bank_transit_number',
            field=models.CharField(blank=True, help_text='5-digit transit number', max_length=10),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG/PNG, max 5 MB)', null=True, upload_to='caregiver_avatars/'),
        ),
    ]
