# Generated by Django 6.0.7 on 2026-08-05 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_caregiver_profile_image_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='True after one-time activation fee is paid')),
                ('activation_paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Weekend Respite Care"', max_length=120)),
                ('care_type', models.CharField(choices=[('senior_elder', 'Senior / Elder Care'), ('dementia', 'Dementia & Alzheimer'), ('palliative', 'Palliative Care'), ('post_surgery', 'Post-Surgery Recovery'), ('postpartum', 'Postpartum Care'), ('companion', 'Companion Care'), ('mobility', 'Mobility Assistance'), ('live_in', 'Live-In Care'), ('overnight', 'Overnight Care'), ('respite', 'Respite Care'), ('other', 'Other')], max_length=30)),
                ('city', models.CharField(help_text='Neighbourhood or city, e.g. "Nepean" or "Ottawa"', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Details about the care needed, patient needs, home environment, etc.')),
                ('hours_per_week', models.PositiveSmallIntegerField(blank=True, help_text='Estimated weekly hours', null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Offered rate in CAD/hr', max_digits=6, null=True)),
                ('schedule', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('flexible', 'Flexible'), ('live_in', 'Live-In'), ('overnight', 'Overnight')], default='flexible', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Desired start date (leave blank if flexible)', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
