# Generated by Django 6.0.7 on 2026-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_employer_profile_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='care_type',
            field=models.CharField(blank=True, choices=[('senior_elder', 'Senior / Elder Care'), ('dementia', 'Dementia & Alzheimer'), ('palliative', 'Palliative Care'), ('post_surgery', 'Post-Surgery Recovery'), ('postpartum', 'Postpartum Care'), ('companion', 'Companion Care'), ('mobility', 'Mobility Assistance'), ('live_in', 'Live-In Care'), ('overnight', 'Overnight Care'), ('respite', 'Respite Care'), ('psw_general', 'General PSW'), ('other', 'Other')], help_text='Primary type of care this caregiver provides', max_length=30),
        ),
    ]
