# Generated by Django 6.0.7 on 2026-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_add_care_type_to_caregiver_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='care_type',
            field=models.TextField(blank=True, help_text='Comma-separated care type keys e.g. senior_elder,dementia'),
        ),
    ]
