# Generated by Django 6.0.7 on 2026-08-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_care_type_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.PositiveIntegerField(help_text='DirectConversation PK — soft FK to avoid circular import')),
                ('negotiated_rate', models.DecimalField(decimal_places=2, help_text='Agreed hourly rate in CAD', max_digits=6)),
                ('message', models.CharField(blank=True, help_text='Optional note from caregiver', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('booked', 'Booked & Paid'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_proposal', to='Account.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
