# Generated by Django 6.0.7 on 2026-08-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_booking_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('activation', 'Account Activation Fee'), ('booking', 'Shift Booking')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged in CAD', max_digits=8)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=12)),
                ('payment_reference', models.CharField(blank=True, help_text='Stripe / simulated payment reference', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Human-readable summary, e.g. "Shift #4 — Jane Doe, 3 hrs"', max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer_payments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_payments', to='Account.shift')),
            ],
            options={
                'verbose_name': 'Employer Payment',
                'verbose_name_plural': 'Employer Payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
