# Generated by Django 6.0.7 on 2026-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_employer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproposal',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True once the recipient (employer) has opened the conversation'),
        ),
        migrations.AddField(
            model_name='employerpayment',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='True after the employer has viewed the payment history page'),
        ),
    ]
