# Generated by Django 6.0.7 on 2026-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_proposal_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='How many hours the caregiver is booked for (e.g. 4.0)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
