# Generated by Django 6.0.5 on 2026-08-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_dispute_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_date', '-start_time']},
        ),
        migrations.AddField(
            model_name='employerpayment',
            name='admin_seen',
            field=models.BooleanField(default=False, help_text='True after the admin has viewed the employer payments page'),
        ),
    ]
