# Generated by Django 6.0.7 on 2026-08-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_bookingproposal_id_alter_caregiverdocument_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='last_doc_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a "complete your documents" reminder email was sent', null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='last_profile_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a "complete your profile" reminder email was sent', null=True),
        ),
    ]
