# Generated by Django 6.0.7 on 2026-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_add_reminder_sent_fields_to_caregiver_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='last_activation_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time an "activate your account" reminder was sent', null=True),
        ),
    ]
