# Generated by Django 6.0.7 on 2026-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_add_activation_reminder_to_employer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='activation_modal_dismissed',
            field=models.BooleanField(default=False, help_text='Set to True permanently when caregiver dismisses the activation modal'),
        ),
    ]
