# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_add_activation_modal_dismissed_to_caregiver_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='last_profile_photo_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a "upload your profile photo" reminder email was sent', null=True),
        ),
    ]