# Generated by Django 6.0.7 on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_add_last_profile_photo_reminder_sent_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FincraCadAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (active)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('interac_email', models.CharField(blank=True, help_text='Interac collection alias (e.g. merchantname@fincra.ca)', max_length=254)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fincra CAD Collection Account',
                'verbose_name_plural': 'Fincra CAD Collection Accounts',
            },
        ),
        migrations.CreateModel(
            name='FincraCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('virtual_account', models.CharField(blank=True, max_length=100)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_currency', models.CharField(blank=True, max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='successful', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Fincra Collection',
                'verbose_name_plural': 'Fincra Collections',
            },
        ),
        migrations.CreateModel(
            name='InteracPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('activation', 'Account Activation Fee'), ('booking', 'Shift Booking')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interac_payment_requests', to='Account.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interac_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Interac Payment Request',
                'verbose_name_plural': 'Interac Payment Requests',
            },
        ),
    ]