"""
Django settings for GETMECARE project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from the project root, overriding any existing env vars.
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--$rr@32q-e2p__*03@pcz8@i)@1s&mn8jmy^!ze46)m9@4w)i5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Also allow any Render domain dynamically
if not DEBUG:
    ALLOWED_HOSTS.append('.onrender.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'Caregiver',
    'Account.apps.AccountConfig',
    'AdminApp.apps.AdminappConfig',
    'EmployerApp.apps.EmployerappConfig',
    'CareGiverAcc.apps.CaregiveraccConfig',
    'Chatbot.apps.ChatbotConfig',
]

AUTH_USER_MODEL = 'Account.CustomUser'

AUTHENTICATION_BACKENDS = [
    'Account.backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GETMECARE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'GETMECARE.context_processors.sidebar_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GETMECARE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Note: don't list app static dirs here — Django finds those automatically
# via APP_DIRS. Only add project-level static folders outside of any app.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static file compression via whitenoise (also set in STORAGES below)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Custom user model
AUTH_USER_MODEL = 'Account.CustomUser'

SITE_ID = 1

# ── Media files (user uploads) ──────────────────────────────────
# In production (Render):  uploads go to ImageKit so they survive deploys.
# In development (local):  uploads stay in the media/ folder.
IMAGEKIT_PRIVATE_KEY  = os.getenv('IMAGEKIT_PRIVATE_KEY', '')
IMAGEKIT_PUBLIC_KEY   = os.getenv('IMAGEKIT_PUBLIC_KEY', '')
IMAGEKIT_URL_ENDPOINT = os.getenv('IMAGEKIT_URL_ENDPOINT', '')
IMAGEKIT_FOLDER       = os.getenv('IMAGEKIT_FOLDER', 'getmecare')

USE_IMAGEKIT = False  # disabled — using local disk storage

# Decide which media-file backend to use.
# Django 5.1+ reads STORAGES['default'] — DEFAULT_FILE_STORAGE is ignored.
_use_imagekit_storage = False  # always local disk

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Django 5.1+ canonical storage config (replaces DEFAULT_FILE_STORAGE)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Groq API Configuration
GROQ_API_KEY = os.getenv('GROQ_API_KEY')

# ── Fincra Payment Gateway ──────────────────────────────────
FINCRA_SECRET_KEY    = os.getenv('FINCRA_SECRET_KEY')
FINCRA_PUBLIC_KEY    = os.getenv('FINCRA_PUBLIC_KEY')
FINCRA_WEBHOOK_KEY   = os.getenv('FINCRA_WEBHOOK_KEY')
FINCRA_BASE_URL      = os.getenv('FINCRA_BASE_URL', 'https://sandboxapi.fincra.com')
FINCRA_BUSINESS_ID   = os.getenv('FINCRA_BUSINESS_ID', '')
# Currency used for Fincra checkout.  NGN supports card, bank_transfer and
# payAttitude.  USD only supports card.  When using NGN, USD prices are
# auto-converted using FINCRA_USD_TO_NGN_RATE.
FINCRA_CURRENCY      = os.getenv('FINCRA_CURRENCY', 'USD')
# Approximate USD→NGN rate used for checkout conversion.
# Update this periodically to match the real market rate.
FINCRA_USD_TO_NGN_RATE = float(os.getenv('FINCRA_USD_TO_NGN_RATE', '1580'))

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
