# Generated by Django 6.0.7 on 2026-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question shown to visitors.', max_length=255)),
                ('answer', models.TextField(help_text='The full answer body.')),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing & Rates'), ('how_it_works', 'How It Works'), ('verification', 'Caregiver Verification'), ('scheduling', 'Scheduling'), ('payments', 'Payments'), ('caregivers', 'For Caregivers'), ('coverage', 'Coverage'), ('support', 'Support')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Unchecked hides this FAQ from the public site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Personal Support Worker (PSW)', max_length=120)),
                ('slug', models.SlugField(help_text='URL-friendly identifier used in links.', max_length=130, unique=True)),
                ('short_description', models.CharField(help_text='One-line summary shown on the service cards.', max_length=255)),
                ('description', models.TextField(help_text='Full description shown on the service detail page.')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-heartbeat', max_length=50)),
                ('rate', models.CharField(blank=True, help_text='e.g. From $28 CAD/hr', max_length=50)),
                ('tag', models.CharField(blank=True, help_text='Badge text, e.g. Most Popular', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Unchecked hides this service from the public site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
