# Generated by Django 6.0.5 on 2026-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image (optional). Falls back to icon.', null=True, upload_to='services/'),
        ),
    ]
