# Generated by Django 6.0.5 on 2026-08-13 11:01

from django.db import migrations


def seed_services(apps, schema_editor):
    Service = apps.get_model('AdminApp', 'Service')
    services = [
        {
            'title': 'Personal Support Worker (PSW)',
            'slug': 'personal-support-worker-psw',
            'short_description': 'Certified PSWs provide hands-on daily care — bathing, grooming, dressing, medication reminders, mobility support, and more.',
            'description': 'Certified PSWs provide hands-on daily care — bathing, grooming, dressing, medication reminders, mobility support, and more.',
            'icon': 'fa-heartbeat',
            'rate': 'From $28 CAD/hr',
            'tag': 'Most Popular',
            'order': 1,
            'is_active': True,
        },
        {
            'title': 'In-Home Senior Care',
            'slug': 'in-home-senior-care',
            'short_description': 'Compassionate, respectful care for aging parents and seniors living independently — companionship, light housekeeping, and assistance with daily routines.',
            'description': 'Compassionate, respectful care for aging parents and seniors living independently — companionship, light housekeeping, and assistance with daily routines.',
            'icon': 'fa-user-nurse',
            'rate': 'From $26 CAD/hr',
            'tag': 'Senior Care',
            'order': 2,
            'is_active': True,
        },
        {
            'title': 'Dementia & Alzheimer Care',
            'slug': 'dementia-alzheimer-care',
            'short_description': 'Specialist caregivers trained in dementia-specific communication, safety protocols, and behaviour management.',
            'description': 'Specialist caregivers trained in dementia-specific communication, safety protocols, and behaviour management.',
            'icon': 'fa-brain',
            'rate': 'From $32 CAD/hr',
            'tag': 'Specialist',
            'order': 3,
            'is_active': True,
        },
        {
            'title': 'Postpartum & Newborn Care',
            'slug': 'postpartum-newborn-care',
            'short_description': 'Trained postpartum caregivers support new mothers during recovery — infant care, feeding support, and emotional reassurance.',
            'description': 'Trained postpartum caregivers support new mothers during recovery — infant care, feeding support, and emotional reassurance.',
            'icon': 'fa-baby',
            'rate': 'From $30 CAD/hr',
            'tag': 'Postpartum',
            'order': 4,
            'is_active': True,
        },
        {
            'title': 'Palliative & End-of-Life Care',
            'slug': 'palliative-end-of-life-care',
            'short_description': 'Compassionate caregivers providing comfort-focused support for clients in their final stages of life.',
            'description': 'Compassionate caregivers providing comfort-focused support for clients in their final stages of life.',
            'icon': 'fa-heart',
            'rate': 'From $34 CAD/hr',
            'tag': 'Palliative',
            'order': 5,
            'is_active': True,
        },
        {
            'title': 'Post-Surgery Recovery Care',
            'slug': 'post-surgery-recovery-care',
            'short_description': 'Short-term intensive support following hospital discharge — wound care reminders, physiotherapy exercises, and medication schedules.',
            'description': 'Short-term intensive support following hospital discharge — wound care reminders, physiotherapy exercises, and medication schedules.',
            'icon': 'fa-procedures',
            'rate': 'From $30 CAD/hr',
            'tag': 'Recovery',
            'order': 6,
            'is_active': True,
        },
        {
            'title': 'Companionship & Wellbeing',
            'slug': 'companionship-wellbeing',
            'short_description': 'Friendly, vetted caregivers who provide regular social interaction, light activity support, and emotional wellbeing for seniors living alone.',
            'description': 'Friendly, vetted caregivers who provide regular social interaction, light activity support, and emotional wellbeing for seniors living alone.',
            'icon': 'fa-smile',
            'rate': 'From $24 CAD/hr',
            'tag': 'Companionship',
            'order': 7,
            'is_active': True,
        },
        {
            'title': 'Live-In Caregiver',
            'slug': 'live-in-caregiver',
            'short_description': 'Around-the-clock in-home care for clients who need continuous support — consistent, familiar, and responsive care throughout the day and night.',
            'description': 'Around-the-clock in-home care for clients who need continuous support — consistent, familiar, and responsive care throughout the day and night.',
            'icon': 'fa-home',
            'rate': 'From $220 CAD/day',
            'tag': 'Live-In',
            'order': 8,
            'is_active': True,
        },
    ]
    for s in services:
        Service.objects.get_or_create(slug=s['slug'], defaults=s)


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_add_service_image'),
    ]

    operations = [
        migrations.RunPython(seed_services, reverse_code=migrations.RunPython.noop),
    ]
