# Generated by Django 6.0.5 on 2026-08-13 11:08

from django.db import migrations


def update_descriptions(apps, schema_editor):
    Service = apps.get_model('AdminApp', 'Service')
    updates = {
        'personal-support-worker-psw': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Personal hygiene &amp; grooming</li>'
            '<li><i class="fas fa-check"></i> Medication reminders</li>'
            '<li><i class="fas fa-check"></i> Mobility &amp; transfer assistance</li>'
            '<li><i class="fas fa-check"></i> Meal preparation &amp; feeding</li>'
            '<li><i class="fas fa-check"></i> Bowel &amp; bladder care</li>'
            '</ul>',
        },
        'in-home-senior-care': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Companionship &amp; social engagement</li>'
            '<li><i class="fas fa-check"></i> Cognitive stimulation activities</li>'
            '<li><i class="fas fa-check"></i> Light housekeeping &amp; laundry</li>'
            '<li><i class="fas fa-check"></i> Grocery shopping &amp; errands</li>'
            '<li><i class="fas fa-check"></i> Transportation to appointments</li>'
            '</ul>',
        },
        'dementia-alzheimer-care': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Dementia-friendly communication</li>'
            '<li><i class="fas fa-check"></i> Wandering &amp; safety monitoring</li>'
            '<li><i class="fas fa-check"></i> Routine-based daily structure</li>'
            '<li><i class="fas fa-check"></i> Sundowning management</li>'
            '<li><i class="fas fa-check"></i> Family update &amp; reporting</li>'
            '</ul>',
        },
        'postpartum-newborn-care': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Newborn feeding &amp; latching support</li>'
            '<li><i class="fas fa-check"></i> Safe sleep guidance</li>'
            '<li><i class="fas fa-check"></i> Overnight newborn care</li>'
            '<li><i class="fas fa-check"></i> Postpartum maternal support</li>'
            '<li><i class="fas fa-check"></i> Light housekeeping &amp; meal prep</li>'
            '</ul>',
        },
        'palliative-end-of-life-care': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Comfort &amp; dignity-focused care</li>'
            '<li><i class="fas fa-check"></i> Pain &amp; symptom observation</li>'
            '<li><i class="fas fa-check"></i> Emotional support for family</li>'
            '<li><i class="fas fa-check"></i> Coordination with health teams</li>'
            '<li><i class="fas fa-check"></i> 24/7 shift availability</li>'
            '</ul>',
        },
        'post-surgery-recovery-care': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Wound care observation &amp; reminders</li>'
            '<li><i class="fas fa-check"></i> Physiotherapy exercise support</li>'
            '<li><i class="fas fa-check"></i> Medication schedule management</li>'
            '<li><i class="fas fa-check"></i> Mobility &amp; fall prevention</li>'
            '<li><i class="fas fa-check"></i> Appointment transport</li>'
            '</ul>',
        },
        'companionship-wellbeing': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> Conversation &amp; social activities</li>'
            '<li><i class="fas fa-check"></i> Games, reading &amp; hobbies</li>'
            '<li><i class="fas fa-check"></i> Outdoor walks &amp; outings</li>'
            '<li><i class="fas fa-check"></i> Light errands &amp; shopping</li>'
            '<li><i class="fas fa-check"></i> Wellbeing check-ins &amp; reporting</li>'
            '</ul>',
        },
        'live-in-caregiver': {
            'description': '<ul>'
            '<li><i class="fas fa-check"></i> 24-hour presence &amp; oversight</li>'
            '<li><i class="fas fa-check"></i> Night-time care &amp; monitoring</li>'
            '<li><i class="fas fa-check"></i> Full daily personal care routine</li>'
            '<li><i class="fas fa-check"></i> Household management</li>'
            '<li><i class="fas fa-check"></i> Consistent schedule &amp; familiarity</li>'
            '</ul>',
        },
    }
    for slug, fields in updates.items():
        Service.objects.filter(slug=slug).update(**fields)


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_seed_services'),
    ]

    operations = [
        migrations.RunPython(update_descriptions, reverse_code=migrations.RunPython.noop),
    ]
